config/routes.rb
Apisio::Application.routes.draw do

  get "errors/404"
  get "errors/500"

  match "/signin" => "sessions#signin"
  match "/signout" => "sessions#signout"

  match '/auth/:service/callback' => 'sessions#create' 
  match '/auth/failure' => 'sessions#failure'
  match '/auth/:provider' => "application#omniauth"
  match '/users/password' => "users#password"
  match '/feed' => "users#feed"
  match '/activity' => "users#allfeed"
  match '/activity/:id' => "users#showfeed"

  match ':id/following' => 'follows#index', :view => 'following', :constraints => { :id => /[0-9A-Za-z\-\.\%20]+/ }
  match ':id/followers' => 'follows#index', :view => 'followers', :constraints => { :id => /[0-9A-Za-z\-\.\%20]+/ }
  
  match '/login' => 'sessions#new'
  match '/logout' => 'sessions#destroy'
  match '/password/:id' => 'users#password'
  match '/about' => 'static#about'
  match '/users/pollallfeed' => 'users#pollallfeed'
  match '/users/pollfeed' => 'users#pollfeed'
  match '/statuses/pollfeed' => 'statuses#pollfeed'
  match '/follows/block/:id' => 'follows#block'
  match '/follows/unblock/:id' => 'follows#unblock'

  match '/search/:id' => 'apis#search', :constraints => { :id => /[0-9A-Za-z\-\.\%20]+/ }
  match '/:id/import' => 'apis#import', :constraints => { :id => /[0-9A-Za-z\-\.\%20]+/ }
  match '/:id/export' => 'apis#export', :constraints => { :id => /[0-9A-Za-z\-\.\%20]+/ }
  match '/apis/wadl_import' => 'apis#wadl_import'
  match '/explorer' => 'explorers#index'
  
  match '/bechtel' => 'sessions#bechtel' #Bechtel OAuth Login
  match '/sessions' => 'sessions#index' #Bechtel OAuth Login
  match '/logins' => 'static#login'
  

  resources :users
  resources :sessions
  resources :follows
  resources :statuses
  resources :apis
  resources :mashups, :constraints => { :id => /[0-9A-Za-z\-\.\%20]+/ }
  resources :explorers
  resources :parameters
  resources :resources
  
  
  match '/api' => 'static#api'
  match ':id' => 'apis#show', :constraints => { :id => /[0-9A-Za-z\-\.\%20]+/ }
  
  match '*a', :to => 'errors#404'

  root :to => 'static#index'

end

app/models/api.rb
class Api < ActiveRecord::Base
  belongs_to :user
  has_many :statuses
  has_many :resources
  has_many :mashups
  
  validates :name, :presence =>true
  validates :apiurl, :presence =>true
  validates :imageurl, :presence =>true
  validates :description, :presence =>true
  validates :apidocurl, :presence =>true
  validates :category, :presence =>true
end

app/controllers/apis_controller.rb
class ApisController < ApplicationController
  # GET /apis
  # GET /apis.json
  def index
    
    @page = params[:page].to_i
    if @page == 0
      @page = 1
    end
    @page = @page + 1

    @apis = Api.paginate :page => params[:page], :order=>"name", :per_page => 100
     
    # respond_to do |format| 
    #   format.html # index.html.erb
    #   format.json { render json: @apis }
    # end
  end

  def search
    if request.url.index('localhost')
      @apis = Api.paginate :page => params[:page], :conditions => ['name LIKE ? or description LIKE ? or category LIKE ? or provider LIKE ?', '%' + params[:id] + '%', '%' + params[:id] + '%', '%' + params[:id] + '%', '%' + params[:id] + '%'], :order=>"name", :per_page => 100
     else
      @apis = Api.paginate :page => params[:page], :conditions => ['name ILIKE ? or description ILIKE ? or category ILIKE ? or provider LIKE ?', '%' + params[:id] + '%', '%' + params[:id] + '%', '%' + params[:id] + '%', '%' + params[:id] + '%'], :order=>"name", :per_page => 100
    end

    respond_to do |format|
      format.html { render :index }
      format.json { render json: @apis }
    end
  end

  # GET /apis/1
  # GET /apis/1.json
  def show
    if params[:id] and isNumeric(params[:id])
      @api = Api.find(params[:id])
    else
      
      if request.url.index('localhost')
        @api = Api.find(:first, :conditions => ['name LIKE ?', params[:id]])
       else
        @api = Api.find(:first, :conditions => ['name ILIKE ?', params[:id]])
      end
    
    end
    
    if @api
      
      @follow = Follow.find(:first, :conditions => ["user_id = ? and follow_id = ?", session[:user_id], @api.id])      
      @followers = Follow.count(:conditions => ["follow_id = ?", @api.id])
      
      @resources = Resource.find(:all, :conditions => ["api_id = ?", @api.id], :order => "resourcename, resourcemethod")
    
    else
      redirect_to "/errors/404"
    end
    
    # respond_to do |format|
    #   format.html # show.html.erb
    #   format.json { render json: @api }
    # end
  end

  # GET /apis/new
  # GET /apis/new.json
  def new
    @api = Api.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @api }
    end
  end

  # GET /apis/1/edit
  def edit
    if params[:id] and isNumeric(params[:id])
      @api = Api.find(params[:id])
    else
      
      if request.url.index('localhost')
        @api = Api.find(:first, :conditions => ['name LIKE ?', params[:id]])
      else
        @api = Api.find(:first, :conditions => ['name ILIKE ?', params[:id]])
      end
    
    end
    
  end

  # POST /apis
  # POST /apis.json
  def create
    @api = Api.new(params[:api])

    respond_to do |format|
      if @api.save
        
        @status = Status.new
        @status.user_id = session["user_id"]
        @status.api_id = @api.id
        @status.message = "Created " + @api.name.capitalize + " API"
        @status.save
        
        format.html { redirect_to '/' + URI.escape(@api.name), notice: 'Api was successfully created.' }
        format.json { render json: @api, status: :created, location: @api }
      else
        format.html { render action: "new" }
        format.json { render json: @api.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /apis/1
  # PUT /apis/1.json
  def update
    if params[:id] and isNumeric(params[:id])
      @api = Api.find(params[:id])
    else
      
      if request.url.index('localhost')
        @api = Api.find(:first, :conditions => ['name LIKE ?', params[:id]])
      else
        @api = Api.find(:first, :conditions => ['name ILIKE ?', params[:id]])
      end
    
    end
    
    respond_to do |format|
      if @api.update_attributes(params[:api])
        
        @status = Status.new
        @status.user_id = session["user_id"]
        @status.api_id = @api.id
        @status.message = "Updated " + @api.name.capitalize + " API"
        @status.save
        
        format.html { redirect_to '/' + URI.escape(@api.name), notice: 'Api was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @api.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apis/1
  # DELETE /apis/1.json
  def destroy
    @api = Api.find(params[:id])
    
    if session["user_id"] == @api.user_id  or session["admin"]
    
      @status = Status.new
      @status.user_id = session["user_id"]
      @status.api_id = @api.id
      @status.message = "Deleted " + @api.name.capitalize + " API"
      @status.save
    
      @api.destroy
    
    end

    respond_to do |format|
      format.html { redirect_to apis_url }
      format.json { head :no_content }
    end
  end
  
  def import
    if params[:id] and isNumeric(params[:id])
      @api = Api.find(params[:id])
    else
      
      if request.url.index('localhost')
        @api = Api.find(:first, :conditions => ['name LIKE ?', params[:id]])
       else
        @api = Api.find(:first, :conditions => ['name ILIKE ?', params[:id]])
      end
    
    end
    
  end
  
  def wadl_import
    
    # TODO: Add support for multiple resources in a wadl file

    @api_id =  params[:dump][:api]
    
    # Bail if API doesn't belong to you.
    @api = Api.find(@api_id)
    if @api and (@api.user_id != session["user_id"]) #or !session["admin"]
      return
    end

    @importcount = 0
      
    Resource.delete_all(["api_id = ?", @api_id])
    Parameter.delete_all(["api_id = ?", @api_id])
    
    content =  params[:dump][:file].read


    @doc = Nokogiri::XML(content)

    # Remove appigee or apisio xml namspaces on tags
    @doc.remove_namespaces!

    @doc.search('*/resource').each do |node|
      
      node.search('method').each do |meth|
      
        @resource = Resource.new
        @resource.api_id = @api_id

        @resource.pathurl = node['path']
      
        @resource.resourcemethod =  meth["name"]

        @resource.description =  meth.search('doc').text.gsub(/\s+/, " ").strip

        @resource.docurl =  meth.xpath('doc')[0]["url"]

        # puts "resource name:" + meth.xpath('tags/tag')[0].text 
        meth.search('tags/tag').each do |tag| 
          if tag["primary"] == "true"
            @resource.resourcename = tag.text 
          end
        end

        if meth.xpath('authentication')[0] and meth.xpath('authentication')[0]["required"] == "true" 
          if @api.provider == "bechtel" or meth.xpath('authentication')[0]["type"] == "oauth"
            @resource.authentication = "OAuth"
            @curlauth = ""
          else  
            @resource.authentication = "Basic"
            @curlauth = "-u 'username:password'"
          end
        else
          @resource.authentication = "None"
          @curlauth = ""
        end 
          
        # Build curl statement
        @curltext = "curl -X " + @resource.resourcemethod + " " + @curlauth + " "

        # base url
        @apiurl = @api.apiurl
        if @apiurl[@apiurl.length-1] != "/"
          @apiurl << "/"
        end 
        
        # url path
        @curlexample = meth.xpath('example')[0]["url"] rescue ""
        if @curlexample[0] == "/"
          @apipath = @curlexample[1..@curlexample.length-1]
        else
          @apipath = @curlexample
        end
        # @curltext << @apiurl + @apipath
        @apiurlpath = @apiurl + @apipath
        
        # TODO: add header, parameters, and payload to curl example
        @resource.curlexample = @curltext

        @resource.save 
        
        # Add resource parameters
        @apiparams = ""
        @apiheaders = ""
        @apipayload = ""
        
        meth.search('request/param').each do |param| 
          
          @parameter = Parameter.new
          @parameter.api_id = @api_id
          @parameter.resource_id = @resource.id

          @parameter.paramname = param["name"]
          @parameter.paramtype = param["type"]
          @parameter.paramdefault = param["default"]
          @parameter.paramstyle = param["style"]
          @parameter.description = param.search('doc').text.gsub(/\s+/, " ").strip
          if param["required"]
            @parameter.paramrequired = true
          else
            @parameter.paramrequired = false
          end 
          @parameter.save
          
          # Format curl
          if param["style"] == "header"
            @apiheaders << " -h '" + param["name"] + ": " + param["default"] + "' " rescue ""
          end  
          if param["style"] == "query"
            @apiparams << "&" + param["name"] + "=" + param["default"] rescue ""
          end
          
        end
        
        @payload = meth.search('request/representation/payload').text.gsub(/\s+/, " ").strip
        if !@payload.blank?
          @parameter = Parameter.new
          @parameter.api_id = @api_id
          @parameter.resource_id = @resource.id
          @parameter.payload = @payload
          @parameter.save   
          
          #Format curl
          @apipayload = "-d '" +  @payload + "' "   
        end
        
        # update curl example with parameters, header, and payload
        @resourceudpate = Resource.find(@resource.id)
        if @resourceudpate
          if @apiparams
            @apiparams = "-d '" + @apiparams[1..@apiparams.length-1] + "' " rescue ""
          end
          
          # IF BECHTEL API ADD ADDITIONAL HEADERS
          if @api.privateaccess and @api.provider == "bechtel"
            
            # Add headers to resource
            @parameter = Parameter.new
            @parameter.api_id = @api_id
            @parameter.resource_id = @resource.id
            @parameter.paramname = "X-myPSN-AppKey"
            @parameter.paramtype = "xsd:string"
            @parameter.paramdefault = ENV['APP_KEY']
            @parameter.paramstyle = "header"
            @parameter.description = "Application Key"
            @parameter.paramrequired = true

app/helpers/apis_helper.rb
module ApisHelper
end

app/views/apis/_apis.html.erb
<% @apis.each do |api| %>

	<% if api.privateaccess != true or (api.privateaccess == true and api.provider == "bechtel" and session['provider'] == "bechtel") or (api.privateaccess == true and api.provider == "personal" and session[:user_id] == api.user_id) %>

	  <div class="span3 well">
    
	    <table>
	      <tr><td height="100" colspan="2">
	        <h4><a href="/<%=api.name%>"><%= api.name %></a>
	        (<%= api.category %>)</h4><hr />
	      </td></tr>
	      <tr>
	      <td width="80" height="160" valign="top"><a href="/<%=api.name%>"><img src="<%= api.imageurl %>" style="width:60px; height:auto; margin:5px;" align="left"></a></td>
	      <td valign="top">        
	        <%= api.description[0..140] %>
	      </td>
	    </tr></table>
    
	  </div>

	<% end %>

<% end %>

app/views/apis/_form.html.erb
<%= form_for(@api) do |f| %>
  <% if @api.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@api.errors.count, "error") %> prohibited this api from being saved:</h2>

      <ul>
      <% @api.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.hidden_field :user_id, :value=>session["user_id"] %>
  <div class="input">
    <%= f.text_field :name, :class=>"input-xxlarge focus", :placeholder=>"API Name" %>
  </div>
  <div class="field">
    <%= f.text_field :apiurl, :class=>"input-xxlarge", :placeholder=>"API Base URL" %>
  </div>
  <div class="field">
    <%= f.text_field :apidocurl, :class=>"input-xxlarge", :placeholder=>"API Documentation URL" %>
  </div>
  <div class="field">
    <%= f.text_field :imageurl, :class=>"input-xxlarge", :placeholder=>"API Image URL" %>
  </div>
  <div class="field">
    <%= f.text_area :description, :class=>"input-xxlarge", :placeholder=>"API Description" %>
  </div>
  <div class="field">
    <%= f.select :category, options_for_select([[@api.category], "Advertising", "Business", "Developer", "Enterprise", "Entertainment", "Gaming", "Health", "Location", "Mapping", "Music", "News", "PaaS", "Payments", "Photos", "Search", "Shopping", "Social", "Telephony", "Tool", "Travel", "Video", "Weather", "Other"]), :class => 'input' %>
  </div>
  <div class="field">
    <%= f.check_box :privateaccess, :class=>"input" %> Private API

	  <span class="field" id="providerdiv" style="display:none;">
	    belonging to: <%= f.select :provider, options_for_select([[@api.provider], "personal", session["provider"]]), :class => 'input' %>
	  </span>
  </div>
<br />
  <div class="actions">
    <%= f.submit :class=>"btn btn-primary" %>
  </div>
<% end %>

<script>

$("#api_privateaccess").click(function(){

	// If checked
	if ($("#api_privateaccess").is(":checked"))
	{
		//show the hidden div
		$("#providerdiv").show("fast");
	}
	else
	{
		//otherwise, hide it
		$("#providerdiv").hide("fast");
	}
});
	
</script> 

app/views/apis/edit.html.erb
<h1>Editing API</h1>

<%= render 'form' %>

<%= link_to 'Show', @api %> |
<%= link_to 'Back', apis_path %>

app/views/apis/import.html.erb
<div class="hero-unit">
  
  <h1>Import WADL</h1>

  <a href="<%=@api.apidocurl%>" target="_new"><center><img src="<%= @api.imageurl %>" align="right" style="width:200px; height: auto;"></center></a>
  
  <br />
  <p>
    You can import your existing WADL files (including Apigee WADLs) into our platform to create API resources! <br /><br />
    <strong>WARNING: Importing a WADL will delete your existing API resources!</strong>
  </p>

  <%= form_for :dump, :url=>{:controller=>"apis", :action=>"wadl_import"}, :html => { :multipart => true } do |f| -%>
    <%= f.hidden_field :api, :value => @api.id %>
      <%= f.file_field :file -%>
    <%= f.submit "Upload", :class=>"btn btn-danger", :id=>"followbutton" %>          
  <% end -%>

  <div id="spinner" style="display:none"><%=image_tag("ajax-spinner.gif")%></div>
  <script>
  $(function() {
    $("#followbutton").click(function() {
      $("#spinner").show();
    });
  });
  </script>
    
</div>

app/views/apis/index.html.erb
<h1>API Directory</h1>

<% if controller.action_name == "search" %>
<h2>Search results for <i><%=params[:id]%></i></h2>
<% end %>  

<br /><br />
<div class="row">
<div class="span16">
	
	<div id="statuses">
		<%= render 'apis'%>
	</div>
	
</div>
</div>


<!-- <br />
<p><center><div class="pager"><%= will_paginate @apis, :page_links => false %></div></center></p>
<br /> -->
<!-- <div id="pager" class="pager"><div class="pagination">
	<a class="next_page" rel="next" href="#" onclick="$('.pagination').html('<img src=<%= '"/assets/ajax-spinner.gif"'%>>');$.getScript('/apis?page=<%=@page.to_s%>'); return false;">more</a>
</div></div> -->


<% if session["user_id"]%>
<%= link_to raw('<button class="btn btn-primary"> <i class="icon-plus icon-white"></i> Add API </button>'), new_api_path %>
<% end %>

<br /><br /><br />
<div id="scrollpage" style="display:none;">2</div>
<div id="scrollactive" style="display:none;">false</div>

<script>
	var killScroll = $('#scrollactive').html();
	$(window).scroll(function(){
	        if  ($(window).scrollTop()+200 >= ($(document).height() - ($(window).height()))){
		
				if (killScroll == 'false') { // IMPORTANT - Keeps the loader from fetching more than once.
					killScroll = $('#scrollactive').html("true");
					$.getScript('/apis?page=' + $('#scrollpage').html()); return false;
				}
				
	        }
	});
</script>

app/views/apis/index.js.erb
$("#statuses").append("<%= escape_javascript(render("apis")) %>");
// $("#pager").html('<div class="pagination"><a class="next_page" rel="next" href="#" onclick="<%='$(".pagination").html("<img src=/assets/ajax-spinner.gif>");$.getScript("/apis?page=' + @page.to_s + '");return false;'%>">more</a></div>');
$('#scrollpage').html(<%=@page%>);
$('#scrollactive').html("false");

app/views/apis/new.html.erb
<h1>New API</h1>
<br /><br />

<%= render 'form' %>

<%= link_to 'Back', apis_path %>
<br /><br />