config/routes.rb
Apisio::Application.routes.draw do

  get "errors/404"
  get "errors/500"

  match "/signin" => "sessions#signin"
  match "/signout" => "sessions#signout"

  match '/auth/:service/callback' => 'sessions#create' 
  match '/auth/failure' => 'sessions#failure'
  match '/auth/:provider' => "application#omniauth"
  match '/users/password' => "users#password"
  match '/feed' => "users#feed"
  match '/activity' => "users#allfeed"
  match '/activity/:id' => "users#showfeed"

  match ':id/following' => 'follows#index', :view => 'following', :constraints => { :id => /[0-9A-Za-z\-\.\%20]+/ }
  match ':id/followers' => 'follows#index', :view => 'followers', :constraints => { :id => /[0-9A-Za-z\-\.\%20]+/ }
  
  match '/login' => 'sessions#new'
  match '/logout' => 'sessions#destroy'
  match '/password/:id' => 'users#password'
  match '/about' => 'static#about'
  match '/users/pollallfeed' => 'users#pollallfeed'
  match '/users/pollfeed' => 'users#pollfeed'
  match '/statuses/pollfeed' => 'statuses#pollfeed'
  match '/follows/block/:id' => 'follows#block'
  match '/follows/unblock/:id' => 'follows#unblock'

  match '/search/:id' => 'apis#search', :constraints => { :id => /[0-9A-Za-z\-\.\%20]+/ }
  match '/:id/import' => 'apis#import', :constraints => { :id => /[0-9A-Za-z\-\.\%20]+/ }
  match '/:id/export' => 'apis#export', :constraints => { :id => /[0-9A-Za-z\-\.\%20]+/ }
  match '/apis/wadl_import' => 'apis#wadl_import'
  match '/explorer' => 'explorers#index'
  
  match '/bechtel' => 'sessions#bechtel' #Bechtel OAuth Login
  match '/sessions' => 'sessions#index' #Bechtel OAuth Login
  match '/logins' => 'static#login'
  

  resources :users
  resources :sessions
  resources :follows
  resources :statuses
  resources :apis
  resources :mashups, :constraints => { :id => /[0-9A-Za-z\-\.\%20]+/ }
  resources :explorers
  resources :parameters
  resources :resources
  
  
  match '/api' => 'static#api'
  match ':id' => 'apis#show', :constraints => { :id => /[0-9A-Za-z\-\.\%20]+/ }
  
  match '*a', :to => 'errors#404'

  root :to => 'static#index'

end

app/models/api.rb
class Api < ActiveRecord::Base
  belongs_to :user
  has_many :statuses
  has_many :resources
  has_many :mashups
  
  validates :name, :presence =>true
  validates :apiurl, :presence =>true
  validates :imageurl, :presence =>true
  validates :description, :presence =>true
  validates :apidocurl, :presence =>true
  validates :category, :presence =>true
end

app/models/explorer.rb
class Explorer < ActiveRecord::Base
  belongs_to :user
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :user
end

app/models/mashup.rb
class Mashup < ActiveRecord::Base
  attr_accessible :api_id, :mashupdesc, :mashupimageurl, :mashupname, :mashupurl, :user_id

  belongs_to :user
  belongs_to :api

  validates :mashupname, :presence =>true
  validates :mashupurl, :presence =>true
  validates :mashupimageurl, :presence =>true
  validates :mashupdesc, :presence =>true
  validates_uniqueness_of :mashupname, :on => :create  

end

app/models/parameter.rb
class Parameter < ActiveRecord::Base
  belongs_to :resource
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  belongs_to :api
  has_many :parameters
end

app/models/status.rb
class Status < ActiveRecord::Base
  belongs_to :api
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_uniqueness_of :username, :on => :create  
  has_many :apis
  has_many :statuses
  has_many :follows    
  has_many :explorers    
  has_many :mashups
end

app/helpers/apis_helper.rb
module ApisHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/explorers_helper.rb
module ExplorersHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/mashups_helper.rb
module MashupsHelper
end

app/helpers/parameters_helper.rb
module ParametersHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>APIS.io :: The open-source API directory</title>
    <meta name="description" content="Publish, discover, and experiment with APIs" />
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <!-- Le styles -->

    <style type="text/css">
      body {
        padding-top: 60px;
        /* background-image:url('/assets/connect.png');*/
      }
    </style>
    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="/assets/favicon.ico" />
    <link rel="apple-touch-icon" href="images/apple-touch-icon.png" />
    <link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png" />
    <link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png" />
    <script src="http://google-code-prettify.googlecode.com/svn/trunk/src/prettify.js" type="text/javascript"></script>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

    <link href="/stylesheets/bootstrap.css" rel="stylesheet" type="text/css" />
    <!-- <link href="/stylesheets/bootstrap.responsive.css" rel="stylesheet" type="text/css" /> -->
    <link href="http://google-code-prettify.googlecode.com/svn/trunk/src/prettify.css" rel="stylesheet" type="text/css" />

    <script type="text/javascript" src="/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
    <link rel="stylesheet" href="/fancybox/jquery.fancybox-1.3.4.css" type="text/css" media="screen" />

    <!-- <script src="/javascripts/bootstrap.js"></script> -->
    <!-- <script src="/javascripts/bootstrap-tooltip.js"></script>
    <script src="/javascripts/bootstrap-popover.js"></script> -->
    <script src="/javascripts/bootstrap-modal.js"></script>
    <script src="/javascripts/bootstrap-alerts.js"></script>


    <style type="text/css">
       p.c2 {text-align: right}
       div.c1 {display: none}
    </style>

    <%= yield :head %>
    <%= yield :stylers %>

    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-2483685-25']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

    </script>
    
  </head>
  <body data-spy="scroll" data-target=".subnav" data-offset="50">
    <script type="text/javascript">
      function lookupapi(){
        window.location.replace("/search/" + $('#apisearch').val());
        return false;
      }
    </script>
    
    <!-- Navbar ================================================== -->
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <!-- <div class="container"> -->
		<div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <!a class="brand" href="/"><div class="brand"></div><!/a>
          <div class="nav-collapse">
            <ul class="pull-right nav">
              <li>
                <form onsubmit="return lookupapi();" class="navbar-search pull-left">
                <input class="input-large search-query" type="text" placeholder="search" id="apisearch" name="apisearch" />
                </form>
              </li>
             </ul>
            <ul class="nav">

              <% if session["user_id"] %>
              <li>
                <div class="thumbnail">
				<% if session["photo"] %>	
					<img src="<%= session["photo"] %>" style="width:25px; height: 25px;"/>
				<% else %>
					<%= gravatar_image_tag session["email"], :class => "gravatar", :style=>"width:25px; height: 25px;" rescue ""%> 
				<% end %>
                </div>
              </li>
              <li>  
                <%= link_to session["username"].upcase, "/users/" + session["username"], :title => "Profile" %>     
              </li>
              <% end %>

              <% if session["user_id"] %>
              <li><%= link_to 'Home', '/statuses', :title => "Home", :class=>"active" %></li> 
              <% else %>
              <li><%= link_to 'Home', '/', :title => "Home", :class=>"active" %></li> 
              <% end %>
              <li><%= link_to 'API Directory', '/apis', :title => "API Directory" %></li> 
              <li><%= link_to 'API Explorer', '/explorer', :title => "API Explorer" %></li> 
              <li><%= link_to 'Mashups', '/mashups', :title => "Mashups" %></li> 

              <% if session["user_id"] %>
              <li><%# link_to 'QSOs', '/' + session["username"] + '/contacts', :title => "Social Logbook" %></li> 
              <li><%= link_to 'Logout', '/logout', :title => "Logout" %> </li>
              <% else %>
              <li><%= link_to 'Register/Login', '/logins', :title => "Login" %></li>
              <% end %>

            </ul>
          </div>
        </div>
      </div>
    </div>
    
    <div class="container-fluid">  
      <p id="notice"><%= alert %></p>
		<% if session['provider'] == "bechtel" and controller.controller_name == "explorers"%>
			<b>Authorized Bechtel User Data</b><br />
			Base URI = https://api.mypsn.com/svc1/v2<br /><br />
			Headers:<br />
			X-myPSN-AppKey = <%= ENV['APP_KEY']%> <br />
			Authorization = <%=session['access_token']%>
		<% end %>
      <p class="pull-right">
      <%= link_to image_tag("apisio_blocks2.png"), '/' %>
      </p>
      <br /><br /><br /><br /><br />
      <%= yield :alert %>        
      <%= yield %>
    </div>

    <footer class="footer">
      <div class="container">
        <p>
        <center>
          <% time = Time.new %>
          &copy; <%=time.year%> - APIS.io - <%=link_to "About Us", "/about"%> | <%=link_to "API", "/api"%> | <%=link_to "Twitter", "http://twitter.com/apisio"%> 
        </center>
        </p>
      </div>
    </footer>

    <script>
      $(document).ready(function() {
        $('a[rel]').tooltip();
      });
    </script>

  </body>
</html>

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :api_id %>
  <div class="field">
    <%= f.label :resourcename %>
    <%= f.text_field :resourcename, :class=>"input-xxlarge" %>
  </div>
  <div class="field">
    <%= f.label :pathurl %>
    / <%= f.text_field :pathurl, :class=>"input-xxlarge" %>
  </div>
  <div class="field">
    <%= f.label :resourcemethod %>
    <%= f.select :resourcemethod, options_for_select([[@resource.resourcemethod], "GET", "POST", "PUT", "DELETE"]), :class => 'input' %><br />          
  </div>
  <div class="field">
    <%= f.label :authentication %>
    <%= f.select :authentication, options_for_select([[@resource.authentication], "None", "Basic", "OAuth"]), :class => 'input' %><br />          
  </div>

  <div class="field">
    <%= f.label :curlexample %>
    <%= f.text_field :curlexample, :class=>"input-xxlarge" %>
  </div>
  <div class="field">
    <%= f.label :docurl %>
    <%= f.text_field :docurl, :class=>"input-xxlarge" %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, :class=>"input-xxlarge", :rows=>"5" %>
  </div>
  <div class="actions">
    <%= f.submit :class=>"btn btn-success" %> <%= link_to 'cancel', "/" + @resource.api.name %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing Resource</h1>
<br />
<p class="well">
  <b>Base API:</b> <%=@resource.api.apiurl%><br />
</p>
<div class="row">
<div class="span8">

  <%= render 'form' %>

</div>
<div class="span4">
  
  <p class="pull-right">
    <a href="<%=@resource.api.apidocurl%>" target="_new"><center><img src="<%= @resource.api.imageurl %>" style="width:200px; height: 200px;"></center></a>
  </p>

</div>
</div>

app/views/resources/index.html.erb
<h1>Listing resources</h1>

<table>
  <tr>
    <th>Api</th>
    <th>Resourcename</th>
    <th>Pathurl</th>
    <th>Resourcemethod</th>
    <th>Authentication</th>
    <th>Curlexample</th>
    <th>Docurl</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @resources.each do |resource| %>
  <tr>
    <td><%= resource.api_id %></td>
    <td><%= resource.resourcename %></td>
    <td><%= resource.pathurl %></td>
    <td><%= resource.resourcemethod %></td>
    <td><%= resource.authentication %></td>
    <td><%= resource.curlexample %></td>
    <td><%= resource.docurl %></td>
    <td><%= resource.description %></td>
    <td><%= link_to 'Show', resource %></td>
    <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
    <td><%= link_to 'Destroy', resource, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Resource', new_resource_path %>

app/views/resources/new.html.erb
<h1>New resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Api:</b>
  <%= @resource.api_id %>
</p>

<p>
  <b>Resourcename:</b>
  <%= @resource.resourcename %>
</p>

<p>
  <b>Pathurl:</b>
  <%= @resource.pathurl %>
</p>

<p>
  <b>Resourcemethod:</b>
  <%= @resource.resourcemethod %>
</p>

<p>
  <b>Authentication:</b>
  <%= @resource.authentication %>
</p>

<p>
  <b>Curlexample:</b>
  <%= @resource.curlexample %>
</p>

<p>
  <b>Docurl:</b>
  <%= @resource.docurl %>
</p>

<p>
  <b>Description:</b>
  <%= @resource.description %>
</p>


<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>