config/routes.rb
Apisio::Application.routes.draw do

  get "errors/404"
  get "errors/500"

  match "/signin" => "sessions#signin"
  match "/signout" => "sessions#signout"

  match '/auth/:service/callback' => 'sessions#create' 
  match '/auth/failure' => 'sessions#failure'
  match '/auth/:provider' => "application#omniauth"
  match '/users/password' => "users#password"
  match '/feed' => "users#feed"
  match '/activity' => "users#allfeed"
  match '/activity/:id' => "users#showfeed"

  match ':id/following' => 'follows#index', :view => 'following', :constraints => { :id => /[0-9A-Za-z\-\.\%20]+/ }
  match ':id/followers' => 'follows#index', :view => 'followers', :constraints => { :id => /[0-9A-Za-z\-\.\%20]+/ }
  
  match '/login' => 'sessions#new'
  match '/logout' => 'sessions#destroy'
  match '/password/:id' => 'users#password'
  match '/about' => 'static#about'
  match '/users/pollallfeed' => 'users#pollallfeed'
  match '/users/pollfeed' => 'users#pollfeed'
  match '/statuses/pollfeed' => 'statuses#pollfeed'
  match '/follows/block/:id' => 'follows#block'
  match '/follows/unblock/:id' => 'follows#unblock'

  match '/search/:id' => 'apis#search', :constraints => { :id => /[0-9A-Za-z\-\.\%20]+/ }
  match '/:id/import' => 'apis#import', :constraints => { :id => /[0-9A-Za-z\-\.\%20]+/ }
  match '/:id/export' => 'apis#export', :constraints => { :id => /[0-9A-Za-z\-\.\%20]+/ }
  match '/apis/wadl_import' => 'apis#wadl_import'
  match '/explorer' => 'explorers#index'
  
  match '/bechtel' => 'sessions#bechtel' #Bechtel OAuth Login
  match '/sessions' => 'sessions#index' #Bechtel OAuth Login
  match '/logins' => 'static#login'
  

  resources :users
  resources :sessions
  resources :follows
  resources :statuses
  resources :apis
  resources :mashups, :constraints => { :id => /[0-9A-Za-z\-\.\%20]+/ }
  resources :explorers
  resources :parameters
  resources :resources
  
  
  match '/api' => 'static#api'
  match ':id' => 'apis#show', :constraints => { :id => /[0-9A-Za-z\-\.\%20]+/ }
  
  match '*a', :to => 'errors#404'

  root :to => 'static#index'

end

app/models/mashup.rb
class Mashup < ActiveRecord::Base
  attr_accessible :api_id, :mashupdesc, :mashupimageurl, :mashupname, :mashupurl, :user_id

  belongs_to :user
  belongs_to :api

  validates :mashupname, :presence =>true
  validates :mashupurl, :presence =>true
  validates :mashupimageurl, :presence =>true
  validates :mashupdesc, :presence =>true
  validates_uniqueness_of :mashupname, :on => :create  

end

app/controllers/mashups_controller.rb
class MashupsController < ApplicationController
  # GET /mashups
  # GET /mashups.json
  def index
    
    @page = params[:page].to_i
    if @page == 0
      @page = 1
    end
    @page = @page + 1
    
    @mashups = Mashup.paginate :page => params[:page], :order=>"mashupname", :per_page => 100

    # respond_to do |format|
    #   format.html # index.html.erb
    #   format.json { render json: @mashups }
    # end
  end

  # GET /mashups/1
  # GET /mashups/1.json
  def show
    if params[:id] and isNumeric(params[:id])
      @mashup = Mashup.find(params[:id])
    else
      
      if request.url.index('localhost')
        @mashup = Mashup.find(:first, :conditions => ['mashupname LIKE ?', params[:id]])
      else
        @mashup = Mashup.find(:first, :conditions => ['mashupname ILIKE ?', params[:id]])
      end
    
    end


    if @mashup
      
      @follow = Follow.find(:first, :conditions => ["user_id = ? and follow_id = ?", session[:user_id], @mashup.api_id])      
      @followers = Follow.count(:conditions => ["follow_id = ?", @mashup.api_id])
          
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mashup }
    end
  end

  # GET /mashups/new
  # GET /mashups/new.json
  def new
    @mashup = Mashup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mashup }
    end
  end

  # GET /mashups/1/edit
  def edit
    @mashup = Mashup.find(params[:id])
  end

  # POST /mashups
  # POST /mashups.json
  def create
    @mashup = Mashup.new(params[:mashup])

    respond_to do |format|
      if @mashup.save
        format.html { redirect_to @mashup, notice: 'Mashup was successfully created.' }
        format.json { render json: @mashup, status: :created, location: @mashup }
      else
        format.html { render action: "new" }
        format.json { render json: @mashup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mashups/1
  # PUT /mashups/1.json
  def update
    if params[:id] and isNumeric(params[:id])
      @mashup = Mashup.find(params[:id])
    else
      
      if request.url.index('localhost')
        @mashup = Mashup.find(:first, :conditions => ['mashupname LIKE ?', params[:id]])
      else
        @mashup = Mashup.find(:first, :conditions => ['mashupname ILIKE ?', params[:id]])
      end
    
    end
    
    respond_to do |format|
      if @mashup.update_attributes(params[:mashup])
        format.html { redirect_to @mashup, notice: 'Mashup was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mashup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mashups/1
  # DELETE /mashups/1.json
  def destroy
    @mashup = Mashup.find(params[:id])
    
    if session["user_id"] == @mashup.user_id  or session["admin"]     
      @mashup.destroy 
    end 
    
    respond_to do |format|
      format.html { redirect_to mashups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/mashups_helper.rb
module MashupsHelper
end

app/views/mashups/_form.html.erb
<%= form_for(@mashup) do |f| %>
  <% if @mashup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mashup.errors.count, "error") %> prohibited this mashup from being saved:</h2>

      <ul>
      <% @mashup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user_id, :value=>session["user_id"] %>

  <div class="field">
	<% 
	# @apis = Api.find(:all, :order => "name")
	# @apilist = []
	# @apis.each do |api|
	# 	@apilist.push(api.name, api.id)
	# end
	%>
	<% @apis_array = Api.find(:all, :order => "name").map { |api| [api.name, api.id] } %>
	<%= options_for_select(@apis_array) %>
	
    <%= f.select :api_id, options_for_select([[@mashup.api_id], options_for_select(@apis_array)]), :class => 'input' %>
  </div>

  <div class="input">
    <%= f.text_field :mashupname, :class=>"input-xxlarge focus", :placeholder=>"Mashup Name" %>
  </div>

  <div class="input">
    <%= f.text_field :mashupurl, :class=>"input-xxlarge focus", :placeholder=>"Mashup URL" %>
  </div>

  <div class="input">
    <%= f.text_field :mashupimageurl, :class=>"input-xxlarge focus", :placeholder=>"Mashup Logo URL" %>
  </div>

  <div class="input">
    <%= f.text_area :mashupdesc, :class=>"input-xxlarge focus", :placeholder=>"Mashup Description" %>
  </div>

  <div class="actions">
    <%= f.submit :class=>"btn btn-primary" %>
  </div>
<% end %>

app/views/mashups/_mashups.html.erb
<% @mashups.each do |mashup| %>

  <div class="span3 well">

    <table>
      <tr><td height="100" colspan="2">
        <h4><a href="/mashups/<%=mashup.mashupname%>"><%= mashup.mashupname %></a> via 
        <a href="/<%= mashup.api.name %>"> <img src="<%= mashup.api.imageurl %>" style="width:40px; height: 40px; margin:5px;"></a></h4><hr />
      </td></tr>
      <tr>
      <td width="80" height="150" valign="top"><a href="/mashups/<%=mashup.mashupname%>"><img src="<%= mashup.mashupimageurl %>" style="width:60px; height: 60px; margin:5px;" align="left"></a></td>
      <td valign="top">        
        <%= mashup.mashupdesc[0..140] %>
      </td>
    </tr></table>

  </div>

<% end %>

app/views/mashups/edit.html.erb
<h1>Edit Mashup</h1>
<br /><br />

<%= render 'form' %>

<%= link_to 'Show', @mashup %> |
<%= link_to 'Back', mashups_path %>

app/views/mashups/index.html.erb
<h1>Mashup Directory</h1>

<% if controller.action_name == "search" %>
	<h2>Search results for <i><%=params[:id]%></i></h2>
<% end %>  

<br /><br />
<div class="row-fluid">
	<div class="span16">

		<div id="statuses">
			<%= render 'mashups'%>
		</div>
		
	</div>
</div>


<!-- <br /><p><center><div class="pager"><%= will_paginate @mashups, :page_links => false %></div></center></p><br /> -->
<!-- <div id="pager" class="pager"><div class="pagination">
	<a class="next_page" rel="next" href="#" onclick="$('.pagination').html('<img src=<%= '"/assets/ajax-spinner.gif"'%>>');$.getScript('/mashups?page=<%=@page.to_s%>'); return false;">more</a>
</div></div> -->

<% if session["user_id"]%>
	<%= link_to raw('<button class="btn btn-primary"> <i class="icon-plus icon-white"></i> Add Mashup </button>'), new_mashup_path %>
<% end %>

<br /><br /><br />

<div id="scrollpage" style="display:none;">2</div>
<div id="scrollactive" style="display:none;">false</div>

<script>
	var killScroll = $('#scrollactive').html();
	$(window).scroll(function(){
	        if  ($(window).scrollTop()+200 >= ($(document).height() - ($(window).height()))){
		
				if (killScroll == 'false') { // IMPORTANT - Keeps the loader from fetching more than once.
					killScroll = $('#scrollactive').html("true");
					$.getScript('/mashups?page=' + $('#scrollpage').html()); return false;
				}
				
	        }
	});
</script>

app/views/mashups/index.js.erb
$("#statuses").append("<%= escape_javascript(render("mashups")) %>");
// $("#pager").html('<div class="pagination"><a class="next_page" rel="next" href="#" onclick="<%='$(".pagination").html("<img src=/assets/ajax-spinner.gif>");$.getScript("/mashups?page=' + @page.to_s + '");return false;'%>">more</a></div>');
$('#scrollpage').html(<%=@page%>);
$('#scrollactive').html("false");

app/views/mashups/new.html.erb
<h1>New Mashup</h1>
<br /><br />

<%= render 'form' %>

<%= link_to 'Back', mashups_path %>
<br /><br />

app/views/mashups/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row-fluid">
<div class="span8">

<% if @mashup %>

  
  <h1><img src="<%= @mashup.mashupimageurl %>" style="width:60px; height: 60px;"> <%= @mashup.mashupname %>
  (<%= link_to @mashup.api.name, "/" + @mashup.api.name rescue "" %>)</h1>
  <h2>Registered by <%= link_to @mashup.user.username.capitalize, "/users/" + @mashup.user.username.downcase rescue ""%></h2><br />

  <p class="well"><%= @mashup.mashupdesc %><br /><br /></p>

<% end %>


  <%= link_to 'Back', mashups_path %>
  <% if @mashup.user_id == session["user_id"] or session["admin"] %>
    |
      <%= link_to 'Edit', edit_mashup_path(@mashup) %> |
      <%= link_to 'Destroy', @mashup, confirm: 'Are you sure?', method: :delete %>
  <% end %>
  
  
</div><div class="span4">

<br /><br /><br /><br /><br />
<a href="<%=@mashup.api.apiurl%>" target="_new"><center><img src="<%= @mashup.api.imageurl %>" style="width:200px; height: 200px;"></center></a>

<% if session["user_id"] %>
  
  <center>
  <div id="spinner_<%=@mashup.id.to_s rescue "0"%>" style="display:none"><%=image_tag("ajax-spinner.gif")%></div>
    
  <% if @followers %>
    <h2><a href="<%= "/" + @mashup.api.name + "/followers"%>">Followers: <span id="followercount"><%=@followers%></span></a> </h2>
  <% end %>
  
    
  <div id="userstatus_<%=@mashup.api_id.to_s rescue "0"%>">
  <% if @follow %>
  
    <%= form_for :follow, :url=>{:controller=>"follows", :action=>"create", :id=>@mashup.api_id, :status=>'unfollow' }, :remote => true do |f| %>
      <%= button_tag(raw('<i class="icon-remove icon-white"></i> Unfollow'), :title=>"Unfollow " + @mashup.api.name.capitalize, :class=>"btn btn-danger", :id=>"follow_" + @mashup.id.to_s ) %>
    <% end %>
    
    
  <% else %>
  
    <%= form_for :follow, :url=>{:controller=>"follows", :action=>"create", :id=>@mashup.api_id, :status=>'follow' }, :remote => true do |f| %>
          <%= button_tag(raw('<i class="icon-ok"></i> Follow'), :title=>"Follow " + @mashup.api.name.capitalize, :class=>"btn", :id=>"follow_" + @mashup.id.to_s ) rescue ""%>
    <% end %>                      
    
  <% end %>

  <script>
    setbuttonclick(<%=@mashup.id.to_s rescue "0"%>);
  </script>
  </div>    
  </center>
      
  
<% end %>

</div>
</div> 


</div>