config/routes.rb
Apisio::Application.routes.draw do

  get "errors/404"
  get "errors/500"

  match "/signin" => "sessions#signin"
  match "/signout" => "sessions#signout"

  match '/auth/:service/callback' => 'sessions#create' 
  match '/auth/failure' => 'sessions#failure'
  match '/auth/:provider' => "application#omniauth"
  match '/users/password' => "users#password"
  match '/feed' => "users#feed"
  match '/activity' => "users#allfeed"
  match '/activity/:id' => "users#showfeed"

  match ':id/following' => 'follows#index', :view => 'following', :constraints => { :id => /[0-9A-Za-z\-\.\%20]+/ }
  match ':id/followers' => 'follows#index', :view => 'followers', :constraints => { :id => /[0-9A-Za-z\-\.\%20]+/ }
  
  match '/login' => 'sessions#new'
  match '/logout' => 'sessions#destroy'
  match '/password/:id' => 'users#password'
  match '/about' => 'static#about'
  match '/users/pollallfeed' => 'users#pollallfeed'
  match '/users/pollfeed' => 'users#pollfeed'
  match '/statuses/pollfeed' => 'statuses#pollfeed'
  match '/follows/block/:id' => 'follows#block'
  match '/follows/unblock/:id' => 'follows#unblock'

  match '/search/:id' => 'apis#search', :constraints => { :id => /[0-9A-Za-z\-\.\%20]+/ }
  match '/:id/import' => 'apis#import', :constraints => { :id => /[0-9A-Za-z\-\.\%20]+/ }
  match '/:id/export' => 'apis#export', :constraints => { :id => /[0-9A-Za-z\-\.\%20]+/ }
  match '/apis/wadl_import' => 'apis#wadl_import'
  match '/explorer' => 'explorers#index'
  
  match '/bechtel' => 'sessions#bechtel' #Bechtel OAuth Login
  match '/sessions' => 'sessions#index' #Bechtel OAuth Login
  match '/logins' => 'static#login'
  

  resources :users
  resources :sessions
  resources :follows
  resources :statuses
  resources :apis
  resources :mashups, :constraints => { :id => /[0-9A-Za-z\-\.\%20]+/ }
  resources :explorers
  resources :parameters
  resources :resources
  
  
  match '/api' => 'static#api'
  match ':id' => 'apis#show', :constraints => { :id => /[0-9A-Za-z\-\.\%20]+/ }
  
  match '*a', :to => 'errors#404'

  root :to => 'static#index'

end

app/models/parameter.rb
class Parameter < ActiveRecord::Base
  belongs_to :resource
end

app/controllers/parameters_controller.rb
class ParametersController < ApplicationController
  # GET /parameters
  # GET /parameters.json
  def index
    @parameters = Parameter.all

    respond_to do |format|
      format.html {redirect_to "/"}# index.html.erb
      format.json { render json: @parameters }
    end
  end

  # GET /parameters/1
  # GET /parameters/1.json
  def show
    @parameter = Parameter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @parameter }
    end
  end

  # GET /parameters/new
  # GET /parameters/new.json
  def new
    @parameter = Parameter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @parameter }
    end
  end

  # GET /parameters/1/edit
  def edit
    @parameter = Parameter.find(params[:id])
  end

  # POST /parameters
  # POST /parameters.json
  def create
    @parameter = Parameter.new(params[:parameter])

    respond_to do |format|
      if @parameter.save
        
        @status = Status.new
        @status.user_id = session["user_id"]
        @status.api_id = @parameter.api_id
        @status.message = "Added new " + @parameter.paramstyle.capitalize + " parameter to " + @parameter.resource.resourcename.capitalize + " API"
        @status.save
        
        format.html { redirect_to @parameter, notice: 'Parameter was successfully created.' }
        format.json { render json: @parameter, status: :created, location: @parameter }
        format.js { render :action => 'create.js.coffee', :content_type => 'text/javascript'}
        
      else
        format.html { render action: "new" }
        format.json { render json: @parameter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /parameters/1
  # PUT /parameters/1.json
  def update
    @parameter = Parameter.find(params[:id])
    
    if params[:parameter][:paramstyle] == "header"
      @parameter.paramtype = "xsd:string"
    end

    respond_to do |format|
      if @parameter.update_attributes(params[:parameter])
        
        @status = Status.new
        @status.user_id = session["user_id"]
        @status.api_id = @parameter.api_id
        @status.message = "Updated " + @parameter.paramstyle.capitalize + " parameter to " + @parameter.resource.resourcename.capitalize + " API"
        @status.save
        
        
        format.html { redirect_to '/' + @parameter.resource.api.name, notice: 'Parameter was successfully updated.' }
        # format.html { redirect_to @parameter, notice: 'Parameter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @parameter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parameters/1
  # DELETE /parameters/1.json
  def destroy
    @parameter = Parameter.find(params[:id])
    
    @status = Status.new
    @status.user_id = session["user_id"]
    @status.api_id = @parameter.api_id
    @status.message = "Deleted " + @parameter.paramstyle.capitalize + " parameter from " + @parameter.resource.resourcename.capitalize + " API"
    @status.save
    
    @parameter.destroy

    respond_to do |format|
      format.html { redirect_to parameters_url }
      format.json { head :no_content }
      format.js { render :action => 'destroy.js.coffee', :content_type => 'text/javascript'}
    end
  end
end

app/helpers/parameters_helper.rb
module ParametersHelper
end

app/views/parameters/_form.html.erb
<%= form_for(@parameter) do |f| %>
  <% if @parameter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parameter.errors.count, "error") %> prohibited this parameter from being saved:</h2>

      <ul>
      <% @parameter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :api_id, :value => @parameter.api_id %>
  <%= f.hidden_field :resource_id, :value => @parameter.resource_id %>

  <div class="field">
    <%= f.label "Request Type" %>
  <%= f.select :paramstyle, options_for_select([[@parameter.paramstyle], "header", "parameter", "payload"]), :class => 'input' %><br />          
  </div>
  <div class="field">
    <%= f.label "Name" %>
    <%= f.text_field :paramname %>
  </div>
  <div class="field">
    <%= f.label "Value" %>
    <%= f.text_field :paramdefault %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, :rows=>"5", :class=>"input-xxlarge" %>
  </div>
  <div class="field">
    <%= f.label :payload %>
    <%= f.text_area :payload, :rows=>"5", :class=>"input-xxlarge" %>
  </div>
  <div class="field">
    <%= f.label "Required" %>
    <%= f.check_box :paramrequired %>
  </div><br />
  <div class="actions">
    <%= f.submit :class=>"btn btn-success" %> <%= link_to 'cancel', "/" + @parameter.resource.api.name %>
  </div>
<% end %>

app/views/parameters/edit.html.erb
<h1>Editing Parameter</h1>
<br />
<p class="well">
    <%
    if @parameter.resource.resourcemethod == "GET" 
      @btncolor = "primary"
    elsif @parameter.resource.resourcemethod == "POST" 
      @btncolor = "success"
    elsif @parameter.resource.resourcemethod == "DELETE" 
      @btncolor = "danger"
    elsif @parameter.resource.resourcemethod == "PUT" 
      @btncolor = "inverse"
    end

    if @parameter.resource.authentication == "None"
      @prefix = ''
    else
      @prefix = '<i class="icon-lock icon-white"></i>'
    end   
    %>
  
  <a class="btn disabled btn-large btn-<%=@btncolor%>"><%=raw(@prefix)%> <%= @parameter.resource.resourcemethod  rescue ""%></a>
  <b>/<%=@parameter.resource.pathurl rescue ""%></b>  
  <br /><%=@parameter.resource.description rescue ""%>
</p>
<div class="row">
<div class="span8">

<%= render 'form' %>

</div>
<div class="span4">
  
  <p class="pull-right">
    <a href="<%=@parameter.resource.api.apidocurl%>" target="_new"><center><img src="<%= @parameter.resource.api.imageurl %>" style="width:200px; height: 200px;"></center></a>
  </p>

</div>
</div>

app/views/parameters/index.html.erb
<h1>Listing parameters</h1>

<table>
  <tr>
    <th>Resource</th>
    <th>Paramtype</th>
    <th>Paramname</th>
    <th>Paramvalue</th>
    <th>Paramrequired</th>
    <th>Paramdocurl</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @parameters.each do |parameter| %>
  <tr>
    <td><%= parameter.resource_id %></td>
    <td><%= parameter.paramtype %></td>
    <td><%= parameter.paramname %></td>
    <td><%= parameter.paramvalue %></td>
    <td><%= parameter.paramrequired %></td>
    <td><%= parameter.paramdocurl %></td>
    <td><%= link_to 'Show', parameter %></td>
    <td><%= link_to 'Edit', edit_parameter_path(parameter) %></td>
    <td><%= link_to 'Destroy', parameter, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Parameter', new_parameter_path %>

app/views/parameters/new.html.erb
<h1>New parameter</h1>

<%= render 'form' %>

<%= link_to 'Back', parameters_path %>

app/views/parameters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Resource:</b>
  <%= @parameter.resource_id %>
</p>

<p>
  <b>Paramtype:</b>
  <%= @parameter.paramtype %>
</p>

<p>
  <b>Paramname:</b>
  <%= @parameter.paramname %>
</p>

<p>
  <b>Paramvalue:</b>
  <%= @parameter.paramvalue %>
</p>

<p>
  <b>Paramrequired:</b>
  <%= @parameter.paramrequired %>
</p>

<p>
  <b>Paramdocurl:</b>
  <%= @parameter.paramdocurl %>
</p>


<%= link_to 'Edit', edit_parameter_path(@parameter) %> |
<%= link_to 'Back', parameters_path %>